import prisma from '../src/config/db.js';
import bcrypt from 'bcrypt';

const isDev =
    !process.env.SEED_PASSWORD_ADMIN || process.env.NODE_ENV === 'development';

const SEED_PASSWORD_ADMIN = process.env.SEED_PASSWORD_ADMIN || null;
if (SEED_PASSWORD_ADMIN === null) {
    throw new Error(
        "Seed Failure. Please specify environmental variable 'SEED_PASSWORD_ADMIN'.",
    );
}

const SEED_PASSWORD_USER = process.env.SEED_PASSWORD_USER || null;
if (SEED_PASSWORD_USER === null) {
    throw new Error(
        "Seed Failure. Please specify environmental variable 'SEED_PASSWORD_USER'.",
    );
}

async function prepare_pwd(password) {
    return await bcrypt.hash(
        password,
        await bcrypt.genSalt(),
    );
}

async function seed_table(table_name, table_obj, table_data) {
    try {
        // Seeding Data
        const count = await table_obj.count();
        if (count === 0) {
            await table_obj.createMany({
                data: table_data,
            });

            console.log(`Database seeded ${table_name} successfully!`);
        } else {
            console.log(`Database already contains ${table_name} entries. Skipping seed.`);
        }

    } catch (error) {
        console.error(`Seed for ${table_name} failed:`, error);
        process.exit(1);
    } finally {
        await prisma.$disconnect();
    }
}

async function getUserIdFromEmail(email) {
    return (await prisma.user.findFirst({where: {email }})).id;
}

async function geListIdFromTitle(title) {
    return (await prisma.toDoList.findFirst({where: { title }})).id;
}



async function seed_all() {
    // Users
    const new_users = [
        { email: "admin1@example.com", password: await prepare_pwd(SEED_PASSWORD_ADMIN), role: "ADMIN" },
        { email: "admin2@example.com", password: await prepare_pwd(SEED_PASSWORD_ADMIN), role: "ADMIN" },
        { email: "admin3@example.com", password: await prepare_pwd(SEED_PASSWORD_ADMIN), role: "ADMIN" },
        { email: "user1@example.com", password: await prepare_pwd(SEED_PASSWORD_USER), role: "USER" },
        { email: "user2@example.com", password: await prepare_pwd(SEED_PASSWORD_USER), role: "USER" },
        { email: "user3@example.com", password: await prepare_pwd(SEED_PASSWORD_USER), role: "USER" },
        { email: "user4@example.com", password: await prepare_pwd(SEED_PASSWORD_USER), role: "USER" },
        { email: "user5@example.com", password: await prepare_pwd(SEED_PASSWORD_USER), role: "USER" },
    ];
    await seed_table("user", prisma.user, new_users);

    // Lists
    let list_count = 0;
    const new_lists = []
    for (let i = 0; i < new_users.length; i++) {
        // While not specified as part of the schema, every title generated by seeding here will be unique, 
        // which is helpful for writing seed code.
        new_lists.push({ title: `To-Do List ${++list_count}`, isPublic: false, ownerId: await getUserIdFromEmail(new_users[i].email) });
        new_lists.push({ title: `To-Do List ${++list_count}`, isPublic: true, ownerId: await getUserIdFromEmail(new_users[i].email) });
        // new_lists.push({ title: `To-Do List ${++list_count}`, isPublic: false, ownerId: await getUserIdFromEmail(new_users[i].email) });
        // new_lists.push({ title: `To-Do List ${++list_count}`, isPublic: true, ownerId: await getUserIdFromEmail(new_users[i].email) });
    }
    await seed_table("todolist", prisma.toDoList, new_lists);
    
    // ListItems:
    const new_listitems = [];
    let listitem_count = 0;
    for (let i = 0; i < new_lists.length; i++) {
        new_listitems.push({ name: `Perform Item ${++listitem_count}`, details: null, listId: await geListIdFromTitle(new_lists[i].title) });
        new_listitems.push({ name: `Perform Item ${++listitem_count}`, details: `Item ${listitem_count} details specified here.`, listId: await geListIdFromTitle(new_lists[i].title) });
        // new_listitems.push({ name: `Perform Item ${++listitem_count}`, details: null, listId: await geListIdFromTitle(new_lists[i].title) });
        // new_listitems.push({ name: `Perform Item ${++listitem_count}`, details: `Item ${listitem_count} details specified here.`, listId: await geListIdFromTitle(new_lists[i].title) });
    }
    await seed_table("todolistitem", prisma.toDoListItem, new_listitems);

    // ListNotes:
    const new_listnotes = [];
    let listnote_count = 0;
    for (let i = 0; i < new_lists.length; i++) {
        new_listnotes.push({ name: `Note ${++listnote_count}`, content: `Note ${listnote_count} content goes here.`, listId: await geListIdFromTitle(new_lists[i].title) });
        new_listnotes.push({ name: `Note ${++listnote_count}`, content: `Note ${listnote_count} content goes here.`, listId: await geListIdFromTitle(new_lists[i].title) });
    }
    await seed_table("todolistnote", prisma.toDoListNote, new_listnotes);
}

seed_all();